### ISSUE TITLE
Feature request: Auto box (chest) collection

### ISSUE THREAD

**Issue by axen1** [makermotion/cvkoxp#1]
Hello, can you do auto box collection for the subject?

**Comment by lfvillavicencio** [comment]
hey man! just bought your autolot on your pet or buy oreads!

**Comment by axen1** [comment]
Unfortunately, it is very expensive in our country. What do you think, if you do us a favor and do it, maybe we will be happy as a country?

**Comment by lunderoSAC** [comment]
no thanks, i dont like to see farmers in my server. I kill them a lot on CZ :)

**Comment by lfvillavicencio** [comment]
no thanks, I dont like farmers on my server. I kill them a lot everytime in CZ and Delos =3

**Comment by axen1** [comment]
I'm an occasional player, I play for fun. You're a developer, you need to do this without offending us.

**Comment by muratcankurtulus** [comment]
> Hello, can you do auto box collection for the subject?
@axen1 

This whole thing is based on image processing. Because I do not process any network packages, this request of yours require character movement.

When I read your feature request I thought the chest from the monster can be detected and character can move towards to it. This is possible. but unfortunately this was a weekend project for me and I am not planing to put any additional efforts to this(at least for now.). If someone else wants to do I can merge the pull request.

Sorry.

**Comment by axen1** [comment]
Thank you for the information. Yes, the steps you said need correct image processing. If you do it in the future, I will be one of the first applicants and testers :)

This program is only for the archer I guess is it right?

**Comment by muratcankurtulus** [comment]
Actually it can cast any skill(with range). Not just rogue skills.

**Comment by axen1** [comment]
I understand, so what is the ban risk?

**Comment by muratcankurtulus** [comment]
Software do not intercept the network packages like many other koxps.  No one can prove that you are using koxp "except" someone record the screen and send it to game provider and they accept the video as proof.
